# Generated by Django 4.1 on 2022-08-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
