# Generated by Django 4.1 on 2022-08-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_toy_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='toy',
            name='release_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
